####################################
# 포트 및 프로젝트 명칭 설정
####################################
server:
  port: 80                   # 서버 포트
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true                 # 포트 설정

spring:
  application:
    name: empower            # 프로젝트명 설정



  ####################################
  # JPA 설정
  ####################################
  jpa:
    hibernate:
      ddl-auto: update  # create, update, ...
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true           # SQL 구문 보이기
    properties:
      hibernate:
        format_sql: true     # 포멧 처리해서 보이기
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL8 버전 사용

  ####################################
  # 데이터베이스 설정
  ####################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/empower?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234

  ####################################
  # 로깅 설정
  ####################################
  logging:
    config: classpath:log4j2/log4j2.xml
    level:
      root: info
      org:
        hibernate:
          type:
            descriptor:
              sql: trace
        springframework:
          security:
            web: debug

  ####################################
  # 파일 업로드 설정
  ####################################
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

org:
  zerock:
    upload:
      path: upload



